# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_no', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('vsCntrl', 'vsCntrl'), ('Other', 'Other')], max_length=50)),
                ('test_name', models.CharField(max_length=100)),
                ('test_desc', models.CharField(max_length=250)),
                ('sponsor', models.CharField(max_length=50)),
                ('merch_group', models.CharField(choices=[('Health Care', 'Health Care'), ('Consumables', 'Consumables'), ('Beauty/Personal', 'Beauty/Personal'), ('General Merchandising', 'General Merchandising')], max_length=50)),
                ('success_metric', models.CharField(choices=[('Sales Lift', 'Sales Lift'), ('Other', 'Other')], max_length=50)),
                ('success_desc', models.CharField(max_length=100)),
                ('success_value', models.IntegerField(default=0)),
                ('test_type', models.CharField(choices=[('T&L', 'T&L'), ('Other', 'Other')], max_length=50)),
            ],
        ),
    ]
