# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.IntegerField()),
                ('wave_no', models.IntegerField()),
                ('wave_value', models.CharField(max_length=100)),
                ('pre_start', models.DateField()),
                ('pre_end', models.DateField()),
                ('post_start', models.DateField()),
                ('post_end', models.DateField()),
            ],
        ),
    ]
