# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0003_wavedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_no', models.IntegerField()),
                ('product_no', models.IntegerField()),
                ('product_level_no', models.IntegerField()),
                ('product_tier', models.IntegerField()),
                ('group_no', models.IntegerField()),
            ],
        ),
    ]
